### ISSUE TITLE
Incorrect path in Challenges

### ISSUE THREAD

**Issue by Tikvout** [Callisto01/RiotApiWrapper#1]
Hi,

This is my first issue report on github so I apologise if the etiquette is incorrect.
I noticed the path is incorrect on one of the Challenges methods.

`leaderboardByLevel()`

line 73:
`$path = $this->setPath('/challenges/' . $challengeId . '/leaderboard/by-level/' . $level);`
should be:
`$path = $this->setPath('/challenges/' . $challengeId . '/leaderboards/by-level/' . $level);`

**Comment by Callisto01** [comment]
Hi Tikvout,

Thanks for your feedback! I will take care of correcting this error.

**Comment by Callisto01** [comment]
Fixed in version 2.0.1
